x = input('insira algo:')
print('o tipo primitivo:', type(x))
print('é um espaço?', x.isspace())
print('é numérico?', x.isnumeric())
print('é alfabético?' ,x.isalpha())
print('é alfanumérico?', x.isalnum())
print('está em maiúsculas?', x.isupper())
print('está em minúsculas?', x.islower())
print('está capitalizada?', x.istitle())